/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ManufacturerService } from "../manufacturer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ManufacturerCreateInput } from "./ManufacturerCreateInput";
import { Manufacturer } from "./Manufacturer";
import { ManufacturerFindManyArgs } from "./ManufacturerFindManyArgs";
import { ManufacturerWhereUniqueInput } from "./ManufacturerWhereUniqueInput";
import { ManufacturerUpdateInput } from "./ManufacturerUpdateInput";
import { CarFindManyArgs } from "../../car/base/CarFindManyArgs";
import { Car } from "../../car/base/Car";
import { CarWhereUniqueInput } from "../../car/base/CarWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ManufacturerControllerBase {
  constructor(
    protected readonly service: ManufacturerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Manufacturer })
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createManufacturer(
    @common.Body() data: ManufacturerCreateInput
  ): Promise<Manufacturer> {
    return await this.service.createManufacturer({
      data: data,
      select: {
        country: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Manufacturer] })
  @ApiNestedQuery(ManufacturerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async manufacturers(@common.Req() request: Request): Promise<Manufacturer[]> {
    const args = plainToClass(ManufacturerFindManyArgs, request.query);
    return this.service.manufacturers({
      ...args,
      select: {
        country: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Manufacturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async manufacturer(
    @common.Param() params: ManufacturerWhereUniqueInput
  ): Promise<Manufacturer | null> {
    const result = await this.service.manufacturer({
      where: params,
      select: {
        country: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Manufacturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateManufacturer(
    @common.Param() params: ManufacturerWhereUniqueInput,
    @common.Body() data: ManufacturerUpdateInput
  ): Promise<Manufacturer | null> {
    try {
      return await this.service.updateManufacturer({
        where: params,
        data: data,
        select: {
          country: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Manufacturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteManufacturer(
    @common.Param() params: ManufacturerWhereUniqueInput
  ): Promise<Manufacturer | null> {
    try {
      return await this.service.deleteManufacturer({
        where: params,
        select: {
          country: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/cars")
  @ApiNestedQuery(CarFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Car",
    action: "read",
    possession: "any",
  })
  async findCars(
    @common.Req() request: Request,
    @common.Param() params: ManufacturerWhereUniqueInput
  ): Promise<Car[]> {
    const query = plainToClass(CarFindManyArgs, request.query);
    const results = await this.service.findCars(params.id, {
      ...query,
      select: {
        color: true,
        createdAt: true,
        id: true,

        manufacturer: {
          select: {
            id: true,
          },
        },

        model: true,
        updatedAt: true,
        year: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cars")
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "update",
    possession: "any",
  })
  async connectCars(
    @common.Param() params: ManufacturerWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        connect: body,
      },
    };
    await this.service.updateManufacturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cars")
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "update",
    possession: "any",
  })
  async updateCars(
    @common.Param() params: ManufacturerWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        set: body,
      },
    };
    await this.service.updateManufacturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cars")
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "update",
    possession: "any",
  })
  async disconnectCars(
    @common.Param() params: ManufacturerWhereUniqueInput,
    @common.Body() body: CarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cars: {
        disconnect: body,
      },
    };
    await this.service.updateManufacturer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
