/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { ManufacturerWhereUniqueInput } from "../../manufacturer/base/ManufacturerWhereUniqueInput";
import { ServiceHistoryListRelationFilter } from "../../serviceHistory/base/ServiceHistoryListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

@InputType()
class CarWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  color?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ManufacturerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ManufacturerWhereUniqueInput)
  @IsOptional()
  @Field(() => ManufacturerWhereUniqueInput, {
    nullable: true,
  })
  manufacturer?: ManufacturerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  model?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ServiceHistoryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ServiceHistoryListRelationFilter)
  @IsOptional()
  @Field(() => ServiceHistoryListRelationFilter, {
    nullable: true,
  })
  serviceHistories?: ServiceHistoryListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  year?: IntNullableFilter;
}

export { CarWhereInput as CarWhereInput };
